name: weibo-rank-bot

on:
  schedule:
    - cron: '30 0,6,7,8 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install importlib-metadata==7.1.0
      - name: Check Python version
        run: python --version
      - name: Check installed packages
        run: pip freeze
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL_SECOND }}
          passwd: ${{ secrets.CC_PASSWD_SECOND }}
      - uses: hongyiheng/weibo-rank-bot@v0.0.5
        with:
          webhook: ${{ secrets.WEBHOOK }}
