name: weibo-rank-bot

on:
  schedule:
    - cron: '30 0,6,7,8 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: hongyiheng/weibo-rank-bot@v0.0.5
        with:
          webhook: ${{ secrets.WEBHOOK }}
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
