name: weibo-rank-bot

on:
  schedule:
    - cron: '30 0,6,7,8 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and run Docker container
        run: |
          docker build -t weibo-rank-bot .
          docker run weibo-rank-bot
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL_SECOND }}
          passwd: ${{ secrets.CC_PASSWD_SECOND }}
      - uses: hongyiheng/weibo-rank-bot@v0.0.5
        with:
          webhook: ${{ secrets.WEBHOOK }}
